#!/bin/bash

# Defaults
BATT_TEMP=90        # degrees Celsius
BATT_STAPM=15000    # mW
BATT_SLOW=15000     # mW
BATT_FAST=15000     # mW

AC_TEMP=90          # degrees Celsius
AC_STAPM=15000      # mW
AC_SLOW=25000       # mW
AC_FAST=30000       # mW


# Absolute safety limits
POWER_MIN=3         # Watts
POWER_MAX=30        # Watts
TEMP_MIN=40         # Celsius
TEMP_MAX=100        # Celsius


# Find absolute path to ryzenadj executable
RY=`which ryzenadj`

# Do not refresh by default
refresh=""

# Args: value, min, max
# Returns 0/true if value is a number within range, otherwise returns 1/false
validate () {
    if [[ $1 =~ ^[0-9]+$ && $1 -ge $2 && $1 -le $3 ]]; then
        return 0
    else
        return 1
    fi
}

while true; do
    # TODO: fix flickering
    clear
    sudo $RY -i 2> /dev/null | sed -n -e '5,12p' -e '25,26p'
    echo " w | STAPM limit"
    echo " f | FAST limit"
    echo " s | SLOW limit"
    echo " a | All power limits"
    echo " t | temperature limit"
    echo " r | toggle refreshing"
    echo "---| any key to refresh manually"
    echo " d | set to AC defaults"
    echo " b | set to battery defaults"
    echo " q | quit."
    echo
    echo "https://github.com/FlyGoat/RyzenAdj/wiki/Options"


    # Check for input to exit the loop
    read -s $refresh -n 1 key
    case $key in
        [wW])
            read -p "STAPM (W) = " val
            if validate $val $POWER_MIN $POWER_MAX ; then
                sudo $RY -a $((val*1000))
            fi
            ;;
        [fF])
            read -p "FAST (W) = " val
            if validate $val $POWER_MIN $POWER_MAX ; then
                sudo $RY -b $((val*1000))
            fi
            ;;
        [sS])
            read -p "SLOW (W) = " val
            if validate $val $POWER_MIN $POWER_MAX ; then
                sudo $RY -c $((val*1000))
            fi
            ;;
        [tT])
            read -p "Temp (C) = " val
            if validate $val $TEMP_MIN $TEMP_MAX ; then
                sudo $RY -f $val
            fi
            ;;
        [rR])
            if [ -z $refresh ]; then
                refresh="-t 1"
            else
                refresh=""
            fi
            ;;
        [dD])
            sudo $RY -a $AC_STAPM -b $AC_FAST -c $AC_SLOW -f $AC_TEMP
            clear
            ;;
        [bB])
            sudo $RY -a $BATT_STAPM -b $BATT_FAST -c $BATT_SLOW -f $BATT_TEMP
            clear
            ;;
        [aA])
            read -p "All power limits (W) = " val
            if validate $val $POWER_MIN $POWER_MAX ; then
                val=$((val*1000))
                sudo $RY -a $val -b $val -c $val
            fi
            ;;
        [qQ])
            clear
            break
            ;;
        *)
            ;;
    esac
done
